application:
  name: tournament-tracker
  project: Tournament-tracker
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: tt-psql
routers:
- name: main
  routes:
  - application_name: tournament-tracker
    paths:
    - /